---
# Permit co-located instances for solitary minikube virtual machines.
# antiAffinity: "soft"

# Shrink default JVM heap.
esJavaOpts: "-Xmx128m -Xms128m"
replicas: 1

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "400m"
    memory: "1G"
  limits:
    cpu: "2000m"
    memory: "3G"

# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "do-block-storage"  # CHANGE HERE depends on storage class. 
  resources:
    requests:
      storage: 5G
