#########################
#### Create jaeger collector and query
#########################
- name: Create Template for Jaeger Companents
  ansible.builtin.template:
    src: "{{ role_path }}/templates/jaeger.yaml.j2"
    dest: "{{ temp_folder_path }}/jaeger.yaml"

- name: Apply Jaeger Companents Manifest 
  kubernetes.core.k8s:
    state: present
    src: "{{ temp_folder_path }}/jaeger.yaml"
    namespace: "{{ jaeger.namespace }}"

- name: Wait to k8s API Understande Jaeger Collector and Query
  pause:
    seconds: 180
    
- name: Wait for Jaeger Collector and Query Pods Become Ready
  shell: "kubectl wait --namespace={{ jaeger.namespace }} --for=condition=Ready pods --selector 'app.kubernetes.io/instance={{ jaeger.jaeger_comp.name }}' --timeout=600s"
  register: jaeger_comp_pods_ready

- debug: var=jaeger_comp_pods_ready.stdout_lines

- name: Delete Downloaded Jaeger Companents Manifest
  file:
    path: "{{ temp_folder_path }}/jaeger.yaml"
    state: absent