#########################
#### Create Temprary Test Hotrod App
#########################
- name: Create Hotrod App From Template
  ansible.builtin.template:
    src: "{{ role_path }}/templates/hotrod_jaeger_test_app.yaml.j2"
    dest: "{{ temp_folder_path }}/hotrod_jaeger_test_app.yaml"

- name: Apply Hotrod App Manifest
  kubernetes.core.k8s:
    state: present
    src: "{{ temp_folder_path }}/hotrod_jaeger_test_app.yaml"
    namespace: "{{ jaeger.namespace }}"

- name: Wait for Hotrod App Pod and Service Become Ready
  shell: "kubectl wait --namespace={{ jaeger.namespace }} --for=condition=Ready pods --selector 'app=hotrod' --timeout=600s"
  register: hotrod_app_pods_ready

- debug: var=hotrod_app_pods_ready.stdout_lines

- name: Delete downloaded Hotrod App Manifest
  file:
    path: "{{ temp_folder_path }}/hotrod_jaeger_test_app.yaml"
    state: absent