apiVersion: v1
kind: Pod
metadata:
  name: test-trace-pod
  labels:
    app: hotrod-trace
spec:
  containers:
  - name: curl-container
    image: alpine:latest
    command: ["/bin/sh"]
    args: 
      - "-c"
      - |
        apk update && \
        apk add curl && \
        curl test-hotrod-service:8080/dispatch?customer=646576707374657374 && \
        sleep 3600
    stdin: true
    tty: true
